# Generated by Django 4.0.3 on 2022-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_historico_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_ultima_venda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
