# Generated by Django 4.0.3 on 2022-04-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.medidas'),
        ),
    ]
