# Generated by Django 4.0.3 on 2022-04-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0007_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='somente_contabil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
